name: Web Build + Deployment to GitHub Pages

on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches: 
      - main
      - master
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  PYTHON_VERSION: 3.12.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the Application (Optional Test)
      run: |
        python app.py  # Replace 'app.py' with your project entry file

    - name: Build Static Web Files (if applicable)
      run: |
        mkdir -p build/web
        cp -r static/* build/web/

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: web-build-artifact
        path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4.0.5
      with:
        artifact_name: web-build-artifact
